site_name: touchstone.parser
site_description: Python library for Touchstone .sNp parsing and S-parameter analysis in RF/microwave engineering.
site_author: Surya Mangaraj
repo_url: https://github.com/suryakantamangaraj/touchstone-python

theme:
  name: material
  palette:
    primary: deep purple

nav:
  - Home: index.md
  - API Reference: api.md
