import os
import tempfile
import numpy as np
import pytest

from touchstone.parser import (
    DataFormat,
    FrequencyUnit,
    ParameterType,
    TouchstoneData,
    TouchstoneOptions,
    TouchstoneParser,
    write_snp,
    write_snp_to_string,
)

@pytest.fixture
def mock_data():
    options = TouchstoneOptions(
        frequency_unit=FrequencyUnit.MHZ,
        parameter_type=ParameterType.S,
        data_format=DataFormat.RI,
        reference_impedance=50.0,
    )
    frequency = np.array([1000.0, 2000.0])
    s_params = np.zeros((2, 2, 2), dtype=complex)
    
    s_params[0, 0, 0] = complex(0.5, 0.1)
    s_params[0, 1, 0] = complex(0.8, -0.2)
    s_params[0, 0, 1] = complex(0.8, -0.2)
    s_params[0, 1, 1] = complex(0.4, 0.05)
    
    s_params[1, 0, 0] = complex(0.4, 0.2)
    s_params[1, 1, 0] = complex(0.7, -0.3)
    s_params[1, 0, 1] = complex(0.7, -0.3)
    s_params[1, 1, 1] = complex(0.3, 0.1)
    
    comments = ["Test file", "Generated by touchstone-python"]
    
    return TouchstoneData(
        frequency=frequency,
        s_parameters=s_params,
        options=options,
        comments=comments,
    )

def test_write_snp_to_string_ri(mock_data):
    result = write_snp_to_string(mock_data)
    lines = result.strip().split("\n")
    
    assert "! Test file" in lines
    assert "! Generated by touchstone-python" in lines
    assert "# MHZ S RI R 50.0" in lines
    assert "0.001 0.5 0.1 0.8 -0.2 0.8 -0.2 0.4 0.05" in lines
    assert "0.002 0.4 0.2 0.7 -0.3 0.7 -0.3 0.3 0.1" in lines

def test_round_trip(mock_data):
    content_out = write_snp_to_string(mock_data)
    parsed_data = TouchstoneParser.parse_string(content_out, n_ports=2)
    
    assert len(parsed_data.comments) == 2
    assert parsed_data.comments[0] == "Test file"
    assert parsed_data.options.frequency_unit == FrequencyUnit.MHZ
    assert parsed_data.options.data_format == DataFormat.RI
    np.testing.assert_allclose(parsed_data.frequency, mock_data.frequency)
    np.testing.assert_allclose(parsed_data.s_parameters, mock_data.s_parameters)
